%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /MATLAB Drive/IFACS SP26 Temp Data.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 02-Apr-2026 14:23:13

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:C169";

% Specify column names and types
opts.VariableNames = ["time", "temperature_2m__F_", "CalculatedRadiation_W_m__"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
IFACSSP26TempData = readtable(fullfile(fileparts(mfilename('fullpath')), "IFACS SP26 Temp Data.xlsx"), opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%%Convert output type
IFACS = table2array(IFACSSP26TempData);

time = IFACS(:, 1) .* 3600; % time (s) across 3 days
temperature = IFACS(:, 2); % temperature (deg_F) 
radiation = IFACS(:, 3); % radiation (W/m^2)

% Expand time vector to 1-second resolution by interpolation
t_original = time(:);                % original times (s)
t_start = t_original(1);
t_end = t_original(end);
t_full = (t_start:t_end).';          % 1-second interval column vector

% Interpolate temperature and radiation to the new time base
temperature_full = interp1(t_original, temperature, t_full, 'linear');
radiation_full    = interp1(t_original, radiation,    t_full, 'linear');

% Replace original variables with the expanded versions
time = t_full;
temperature = temperature_full;
radiation = radiation_full;

% Plot temperature and radiation on two y-axes sharing the time x-axis
figure('Name','Temperature and Radiation vs Time','NumberTitle','off');
yyaxis left
plot(time/3600, temperature, '-r', 'LineWidth', 1.2); % time in hours
ylabel('Temperature (°F)');
ylim([min(temperature)-1, max(temperature)+1]);

yyaxis right
plot(time/3600, radiation, '-b', 'LineWidth', 1.0); 
ylabel('Radiation (W/m^2)');
ylim([min(radiation)-0.1*abs(min(radiation)), max(radiation)+0.1*abs(max(radiation))]);

xlabel('Time (hours)');
title('Temperature and Radiation vs Time');
grid on;
legend({'Temperature','Radiation'}, 'Location','best');
%% Prep Data For import to Simulink



% Combine time and temperature into Simulink-importable signals
% Create a two-column matrix: [time_seconds, temperature]
time_temperature = [time, temperature];

% Save to .mat for easy import into Simulink (as workspace variable)
save('time_temperature.mat', 'time_temperature');

% Also create timeseries object (useful for From Workspace or From File blocks)
time_temperature_ts = timeseries(temperature, time);
time_temperature_ts.Name = 'temperature_signal';

% Save timeseries as well
save('time_temperature.mat', 'time_temperature', 'time_temperature_ts', '-append');

% Create radiation time-signal for Simulink (matrix and timeseries)

% Two-column matrix: [time_seconds, radiation]
time_radiation = [time, radiation];

% Save matrix to the same .mat file
save('time_temperature.mat', 'time_radiation', '-append');

% Create timeseries object for radiation
time_radiation_ts = timeseries(radiation, time);
time_radiation_ts.Name = 'radiation_signal';

% Append timeseries to .mat file
save('time_temperature.mat', 'time_radiation_ts', '-append');